### ISSUE TITLE
[Bug] name of first option is empty in winner modal

### ISSUE THREAD

**Issue by F9Uf** [F9Uf/lucky-wheel#2]
When we spin the wheel and the random result is the first item, it will show the empty string in the modal.

**Comment by ThPadelis** [comment]
Can you assign this to me?

**Comment by F9Uf** [comment]
@ThPadelis Sure, if you can help me for this issue

**Comment by F9Uf** [comment]
fixed by this PR https://github.com/F9Uf/lucky-wheel/pull/3
